export const BRANCH_OPTIONS = [
  "B.Tech Computer Science and Engineering in Association With Google",
  "B.Tech Computer Science and Engineering in Association With IBM",
  "B.Tech Computer Science and Engineering",
  "B.Tech Computer Science and Engineering (Artificial Intelligence & Machine Learning)",
  "B.Tech Computer Science and Engineering (Data Science)",
  "B.Tech Information Technology",
  "B.Tech Artificial Intelligence and Machine Learning",
  "B.Tech Data Science",
  "B.Tech Internet of Things (IoT)",
  "B.Tech Cyber Security",
  "B.Tech Robotics and Automation",
  "B.Tech Electronics and Communication Engineering",
  "B.Tech Electronics and Computer Engineering",
  "B.Tech Electrical Engineering",
  "B.Tech Electrical and Electronics Engineering",
  "B.Tech Mechanical Engineering",
  "B.Tech Civil Engineering",
  "B.Tech Artificial Intelligence and Data Science",
  "B.Tech Automobile Engineering",
  "B.Tech Chemical Engineering",
  "B.Tech Biotechnology",
  "BCA (Bachelor of Computer Applications)",
  "BCA (Data Science)",
  "BCA (AI & ML)",
  "MCA (Master of Computer Applications)",
  "M.Tech Computer Science and Engineering",
  "M.Tech Data Science",
  "M.Tech Artificial Intelligence",
  "MBA (Master of Business Administration)",
  "BBA (Bachelor of Business Administration)",
  "B.Com (Bachelor of Commerce)",
  "B.Sc Computer Science",
  "B.Sc Information Technology",
  "B.Sc Data Science",
  "Diploma in Computer Science Engineering",
  "Diploma in Mechanical Engineering",
  "Diploma in Civil Engineering",
  "Diploma in Electrical Engineering"
];
